services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - mssql
    volumes:
      - ./app:/app
      - ./app/logs:/app/logs
    networks:
      - flask-network
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    ports:
      - "14333:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - flask-network
volumes:
  mssql-data:
networks:
  flask-network:
    driver: bridge